Prevent build error after changes in kernel_bind() prototype (#136)
* Prevent build error after changes in kernel_bind() prototype

The following error was observed when building the module with gcc
version 15.2.0 (Debian 15.2.0-14):

  [...]
  tcp.c: In function ‘setup_tcp’:
  tcp.c:86:29: error: passing argument 2 of ‘kernel_bind’ from incompatible pointer type [-Wincompatible-pointer-types]
     86 |     r = kernel_bind(control,(struct sockaddr*) &saddr,sizeof(saddr));
        |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
        |                             |
        |                             struct sockaddr *
  In file included from /usr/src/linux-headers-6.19.6+deb14+1-common/include/net/scm.h:6,
                   from /usr/src/linux-headers-6.19.6+deb14+1-common/include/linux/netlink.h:9,
                   from /usr/src/linux-headers-6.19.6+deb14+1-common/include/uapi/linux/neighbour.h:6,
                   from /usr/src/linux-headers-6.19.6+deb14+1-common/include/linux/netdevice.h:44,
                   from /usr/src/linux-headers-6.19.6+deb14+1-common/include/net/sock.h:46,
                   from tcp.c:32:
  /usr/src/linux-headers-6.19.6+deb14+1-common/include/linux/net.h:347:63: note: expected ‘struct sockaddr_unsized *’ but argument is of type ‘struct sockaddr *’
    347 | int kernel_bind(struct socket *sock, struct sockaddr_unsized *addr, int addrlen);
        |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
  disk.c:45:5: warning: no previous prototype for ‘setup_disk’ [-Wmissing-prototypes]
  [...]

Likely related to linux 0e50474fa514 ("net: Convert proto_ops bind()
callbacks to use sockaddr_unsized")

Build tested only.

Signed-off-by: Eder Zulian <ederfzul@gmail.com>

* Potential fix for pull request finding

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>

---------

Signed-off-by: Eder Zulian <ederfzul@gmail.com>
Co-authored-by: Joe Sylve <Joe.Sylve@gmail.com>
Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>